"""empty message

Revision ID: fa30c6ddd60c
Revises: 139eeb6fada8
Create Date: 2026-05-12 07:55:59.891778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa30c6ddd60c'
down_revision = '139eeb6fada8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        # Dentro do arquivo de migração gerado:
        batch_op.add_column(sa.Column('imagem', sa.String(), nullable=False, server_default='default.jpg'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('imagem')

    # ### end Alembic commands ###
